// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcquireGroup(arg1:string):Promise<void>;

export function BackupAll():Promise<string>;

export function BackupGroup(arg1:string):Promise<string>;

export function ExportNote(arg1:string,arg2:string):Promise<string>;

export function FinishClose():Promise<void>;

export function GetStore():Promise<main.Store>;

export function ImportNote():Promise<main.Note>;

export function LoadNoteContent(arg1:string):Promise<string>;

export function LockedGroups():Promise<Array<string>>;

export function MoveChannelToGroup(arg1:string,arg2:string,arg3:main.Store):Promise<main.Store>;

export function ReleaseGroup():Promise<void>;

export function ReloadStore():Promise<main.Store>;

export function ReplaceNotes(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.ReplaceResult>;

export function RestoreAll():Promise<main.Store>;

export function RestoreGroup():Promise<main.GroupBundle>;

export function SaveStore(arg1:main.Store):Promise<string>;

export function SearchNotes(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Array<main.SearchResult>>;

export function SelectImages():Promise<Array<main.ImageData>>;

export function SystemFonts():Promise<Array<string>>;
