// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcquireGroup(arg1) {
  return window['go']['main']['App']['AcquireGroup'](arg1);
}

export function BackupAll() {
  return window['go']['main']['App']['BackupAll']();
}

export function BackupGroup(arg1) {
  return window['go']['main']['App']['BackupGroup'](arg1);
}

export function ExportNote(arg1, arg2) {
  return window['go']['main']['App']['ExportNote'](arg1, arg2);
}

export function FinishClose() {
  return window['go']['main']['App']['FinishClose']();
}

export function GetStore() {
  return window['go']['main']['App']['GetStore']();
}

export function ImportNote() {
  return window['go']['main']['App']['ImportNote']();
}

export function LoadNoteContent(arg1) {
  return window['go']['main']['App']['LoadNoteContent'](arg1);
}

export function LockedGroups() {
  return window['go']['main']['App']['LockedGroups']();
}

export function MoveChannelToGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveChannelToGroup'](arg1, arg2, arg3);
}

export function ReleaseGroup() {
  return window['go']['main']['App']['ReleaseGroup']();
}

export function ReloadStore() {
  return window['go']['main']['App']['ReloadStore']();
}

export function ReplaceNotes(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ReplaceNotes'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function RestoreAll() {
  return window['go']['main']['App']['RestoreAll']();
}

export function RestoreGroup() {
  return window['go']['main']['App']['RestoreGroup']();
}

export function SaveStore(arg1) {
  return window['go']['main']['App']['SaveStore'](arg1);
}

export function SearchNotes(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchNotes'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectImages() {
  return window['go']['main']['App']['SelectImages']();
}

export function SystemFonts() {
  return window['go']['main']['App']['SystemFonts']();
}
